### ISSUE TITLE
Error when launching the script

### ISSUE THREAD

**Issue by octave-ati** [billyvg/pokemon-go-iv#10]
Hello,

I'm trying to use your app today and when inputing : 
pokemon-go-iv -u email@adress -p mypassword -a google -s recent

It returns this error :

C:\Users\Octave\AppData\Roaming\npm\node_modules\pokemon-go-iv\src\main.js:1
(function (exports, require, module, __filename, __dirname) { import _ from 'lodash';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:513:28)
    at Module._extensions..js (module.js:550:10)
    at Object.require.extensions.(anonymous function) [as .js](C:UsersOctaveAppDataRoamingnpmnode_modulespokemon-go-ivnode_modulesbabel-registerlibnode.js:156:7)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Octave\AppData\Roaming\npm\node_modules\pokemon-go-iv\bin\cli.js:10:17)

Do you know how I can fix this?

**Comment by esminerva** [comment]
Try run it with node 6

**Comment by billyvg** [comment]
I'm looking into this now, but as a workaround you can run the command inside of the package directory:

`cd C:\Users\Octave\AppData\Roaming\npm\node_modules\pokemon-go-iv`

**Comment by billyvg** [comment]
Fixed in ccf444328d1cebe2a594fbf8006b028b1535933c
