### ISSUE TITLE
AssertionError: Current npm version is not supported for development, expected "4.1.2" to satisfy "2.x || 3.x".

### ISSUE THREAD

**Issue by aisbergde** [billyvg/pokemon-go-iv#17]
I pulled the latest version with TortoiseGit
I installed the latest node
I executed this to get the latest npm: "npm install npm@latest -g"
Now my versions are: 
node v6.9.5
npm  v4.1.2

I executed "npm install" in the project folder "D:\Git_Repositories\pokemon-journal"
First time a lot of required modules have been installed but at the end I get an error. Then I tried again but got the same error. It looks like some problems with the npm version. But I have no idea what I should do now.

D:\Git_Repositories\pokemon-journal>npm install

> pokemon-journal@0.2.2 postinstall D:\Git_Repositories\pokemon-journal
> node node_modules/fbjs-scripts/node/check-dev-engines.js package.json

assert.js:85
  throw new assert.AssertionError({
  ^
AssertionError: Current npm version is not supported for development, expected "4.1.2" to satisfy "2.x || 3.x".
    at D:\Git_Repositories\pokemon-journal\node_modules\fbjs-scripts\node\check-dev-engines.js:57:5
    at ChildProcess.exithandler (child_process.js:197:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Germo\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.9.5
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! pokemon-journal@0.2.2 postinstall: `node node_modules/fbjs-scripts/node/check-dev-engines.js package.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pokemon-journal@0.2.2 postinstall script 'node node_modules/fbjs-scripts/node/check-dev-engines.js package.json'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pokemon-journal package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/fbjs-scripts/node/check-dev-engines.js package.json
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pokemon-journal
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pokemon-journal
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Git_Repositories\pokemon-journal\npm-debug.log

D:\Git_Repositories\pokemon-journal>

**Comment by aisbergde** [comment]
sorry, wrong project, I wanted to publish the isse in 
pokemon-journal
