### ISSUE TITLE
Illegal wire type for field Message.Field ResponseEnvelop.PokemonData.deployed_fort_id: 2 (0 expected)

### ISSUE THREAD

**Issue by ls12styler** [billyvg/pokemon-go-iv#3]
Hey!

Whenever I search, I'm getting the following:

```
/Users/broadlea/.nvm/versions/node/v4.2.6/lib/node_modules/pokemon-go-iv/node_modules/pokemon-go-node-api/node_modules/protobufjs/dist/protobuf.js:2938
                        throw(e);
                        ^

Error: Illegal wire type for field Message.Field .ResponseEnvelop.PokemonData.deployed_fort_id: 2 (0 expected)
    at Error (native)
    at ProtoBuf.Reflect.FieldPrototype.decode (/Users/broadlea/.nvm/versions/node/v4.2.6/lib/node_modules/pokemon-go-iv/node_modules/pokemon-go-node-api/node_modules/protobufjs/dist/protobuf.js:3679:23)
    at ProtoBuf.Reflect.MessagePrototype.decode (/Users/broadlea/.nvm/versions/node/v4.2.6/lib/node_modules/pokemon-go-iv/node_modules/pokemon-go-node-api/node_modules/protobufjs/dist/protobuf.js:3238:45)
    at ProtoBuf.Reflect.ElementPrototype.decode (/Users/broadlea/.nvm/versions/node/v4.2.6/lib/node_modules/pokemon-go-iv/node_modules/pokemon-go-node-api/node_modules/protobufjs/dist/protobuf.js:2185:46)
    at ProtoBuf.Reflect.FieldPrototype.decode (/Users/broadlea/.nvm/versions/node/v4.2.6/lib/node_modules/pokemon-go-iv/node_modules/pokemon-go-node-api/node_modules/protobufjs/dist/protobuf.js:3727:33)
    at ProtoBuf.Reflect.MessagePrototype.decode (/Users/broadlea/.nvm/versions/node/v4.2.6/lib/node_modules/pokemon-go-iv/node_modules/pokemon-go-node-api/node_modules/protobufjs/dist/protobuf.js:3238:45)
    at ProtoBuf.Reflect.ElementPrototype.decode (/Users/broadlea/.nvm/versions/node/v4.2.6/lib/node_modules/pokemon-go-iv/node_modules/pokemon-go-node-api/node_modules/protobufjs/dist/protobuf.js:2185:46)
    at ProtoBuf.Reflect.FieldPrototype.decode (/Users/broadlea/.nvm/versions/node/v4.2.6/lib/node_modules/pokemon-go-iv/node_modules/pokemon-go-node-api/node_modules/protobufjs/dist/protobuf.js:3727:33)
    at ProtoBuf.Reflect.MessagePrototype.decode (/Users/broadlea/.nvm/versions/node/v4.2.6/lib/node_modules/pokemon-go-iv/node_modules/pokemon-go-node-api/node_modules/protobufjs/dist/protobuf.js:3238:45)
    at ProtoBuf.Reflect.ElementPrototype.decode (/Users/broadlea/.nvm/versions/node/v4.2.6/lib/node_modules/pokemon-go-iv/node_modules/pokemon-go-node-api/node_modules/protobufjs/dist/protobuf.js:2185:46)
```

The command I'm using is:

```
node node_modules/pokemon-go-iv/bin/app.js -u 'ME@SOMEDOMAIN.COM' -p PASSWORD -a google -l '45.79563208690135,-2.555337905883789' -s iv
```

Any ideas?

**Comment by billyvg** [comment]
Location may need to be an address string instead of lat, long

**Comment by macmanchomp** [comment]
Does this work post update? The update broke the proxy based versions.

**Comment by aisbergde** [comment]
Any ideas regarding this error?
when I use
`-l '56.718226,38.782509'`
I get

> Error: location not found

`-l "56.718226,38.782509"`

> [i] Logging with user: xxxxxxx
> [i] Received Google access token!
> [i] Received API Endpoint: https://pgorelease.nianticlabs.com/plfe/210/rpc
> C:\Users\Germo\AppData\Roaming\npm\node_modules\pokemon-go-iv\node_modules\protobufjs\dist\protobuf.js:2938
>                         throw(e);
>                         ^
> 
> Error: Illegal wire type for field Message.Field .ResponseEnvelop.PokemonData.deployed_fort_id: 2 (0 expected)
>     at Error (native)
>     at ProtoBuf.Reflect.FieldPrototype.decode (C:\Users\Germo\AppData\Roaming\npm\node_modules\pokemon-go-iv\node_modules\protobufjs\dist\protobuf.js:3679:23)
>     at ProtoBuf.Reflect.MessagePrototype.decode (C:\Users\Germo\AppData\Roaming\npm\node_modules\pokemon-go-iv\node_modules\protobufjs\dist\protobuf.js:3238:45)
>     at ProtoBuf.Reflect.ElementPrototype.decode (C:\Users\Germo\AppData\Roaming\npm\node_modules\pokemon-go-iv\node_modules\protobufjs\dist\protobuf.js:2185:46)
>     at ProtoBuf.Reflect.FieldPrototype.decode (C:\Users\Germo\AppData\Roaming\npm\node_modules\pokemon-go-iv\node_modules\protobufjs\dist\protobuf.js:3727:33)
>     at ProtoBuf.Reflect.MessagePrototype.decode (C:\Users\Germo\AppData\Roaming\npm\node_modules\pokemon-go-iv\node_modules\protobufjs\dist\protobuf.js:3238:45)
>     at ProtoBuf.Reflect.ElementPrototype.decode (C:\Users\Germo\AppData\Roaming\npm\node_modules\pokemon-go-iv\node_modules\protobufjs\dist\protobuf.js:2185:46)
>     at ProtoBuf.Reflect.FieldPrototype.decode (C:\Users\Germo\AppData\Roaming\npm\node_modules\pokemon-go-iv\node_modules\protobufjs\dist\protobuf.js:3727:33)
>     at ProtoBuf.Reflect.MessagePrototype.decode (C:\Users\Germo\AppData\Roaming\npm\node_modules\pokemon-go-iv\node_modules\protobufjs\dist\protobuf.js:3238:45)
>     at ProtoBuf.Reflect.ElementPrototype.decode (C:\Users\Germo\AppData\Roaming\npm\node_modules\pokemon-go-iv\node_modules\protobufjs\dist\protobuf.js:2185:46)

And I get the same error using an address like "city, street"

**Comment by billyvg** [comment]
Ugh sorry, I've been traveling... it looks like Niantic pushed an update which has killed off API access?

**Comment by billyvg** [comment]
@aisbergde Please try the latest version and see if it helps

**Comment by aisbergde** [comment]
I get this error:

```
C:\Users\Germo\AppData\Roaming\npm\node_modules\pokemon-go-iv\src\main.js:1
(function (exports, require, module, __filename, __dirname) { import _ from 'lodash';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:513:28)
    at Module._extensions..js (module.js:550:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\Germo\AppData\Roaming\npm\node_modules\pokemon-go-iv\node_modules\babel-register\lib\node.js:156:7)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Germo\AppData\Roaming\npm\node_modules\pokemon-go-iv\bin\cli.js:10:17)

```

**Comment by billyvg** [comment]
Please update to v2.0.3 `npm install -g pokemon-go-iv@2.0.3`

**Comment by aisbergde** [comment]
it works!
