### ISSUE TITLE
`node-gyp rebuild` Error when running 'npm install -g pokemon-go-iv'

### ISSUE THREAD

**Issue by AtraSatraps** [billyvg/pokemon-go-iv#4]
C:\Users\Russet\Documents\GitHub> npm install -g pokemon-go-iv
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
C:\Users\Russet\AppData\Roaming\npm\pokemon-go-iv -> C:\Users\Russet\AppData\Roaming\npm\node_modules\pokemon-go-iv\bin\
app.js

> s2geometry-node@1.3.1 install C:\Users\Russet\AppData\Roaming\npm\node_modules\pokemon-go-iv\node_modules\s2geometry-n
> ode
> node-gyp rebuild

C:\Users\Russet\AppData\Roaming\npm\node_modules\pokemon-go-iv\node_modules\s2geometry-node>if not defined npm_config_no
de_gyp (node "C:\Users\Russet\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\nod
e-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Users\Russet\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\confi
gure.js:449:14)
gyp ERR! stack     at C:\Users\Russet\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:404:11

gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Users\Russet\AppData\Roaming\npm\node_modules\npm\nod
e_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Russet\AppData\Roaming\npm\node_modules\pokemon-go-iv\node_modules\s2geometry-node
gyp ERR! node -v v4.4.7
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
C:\Users\Russet\AppData\Roaming\npm
`-- (empty)

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Users\Russet\AppData\Roaming\npm\node_modules\npm\bin\n
pm-cli.js" "install" "-g" "pokemon-go-iv"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! s2geometry-node@1.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the s2geometry-node@1.3.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the s2geometry-node package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs s2geometry-node
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls s2geometry-node
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Russet\Documents\GitHub\npm-debug.log
npm ERR! code 1

**Comment by LightAMV** [comment]
I need help too man

**Comment by aisbergde** [comment]
I get the same errors, only my node and npm versions are higher:
gyp ERR! node -v v6.3.1
gyp ERR! node-gyp -v v3.3.1
npm ERR! npm  v3.10.3

**Comment by aisbergde** [comment]
to solve my issue i tryed as described here:
https://github.com/nodejs/node-gyp#installation
...
On Windows:
Option 1: Install all the required tools and configurations using Microsoft's windows-build-tools using npm install --global --production windows-build-tools from an elevated PowerShell or CMD.exe (run as Administrator).

what I did:
npm install --global --production windows-build-tools

npm install -g node-gyp
npm install node-gyp@latest

but the issue is still not solved on windows
after windows-build-tools there was some progress, a lot of yellow warnings, but finally a red error:

  win_delay_load_hook.c
C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.c(34): error C2373: '__pfnDliNot
ifyHook2': redefinition; different type modifiers [C:\Users\Germo\AppData\Roaming\npm\node_modules\pokemon-go-iv\node_m
odules\s2geometry-node\build\NativeExtension.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\delayimp.h(134): note: see declaration of '__pfnDliNot
  ifyHook2'
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Germo\AppData\Roaming\npm\node_modules\pokemon-go-iv\node_modules\s2geometry-node
gyp ERR! node -v v6.3.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
C:\Users\Germo\AppData\Roaming\npm
`-- (empty)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "pokemon-go-iv"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! s2geometry-node@1.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the s2geometry-node@1.3.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the s2geometry-node package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs s2geometry-node
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls s2geometry-node
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Git_Repositories\pokemon-journal\npm-debug.log
npm ERR! code 1

D:\Git_Repositories\pokemon-journal>

**Comment by aisbergde** [comment]
The idea was also to update node-gyp, I tried

```
npm uninstall node-gyp
npm install -g node-gyp@latest
```

after installing it is showing
`-- node-gyp@3.4.0

but when I run

```
npm uninstall pokemon-go-iv
npm install -g pokemon-go-iv

```

the error is showing that an older version of node-gyp is used:

> gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
> gyp ERR! cwd C:\Users\Germo\AppData\Roaming\npm\node_modules\pokemon-go-iv\node_modules\s2geometry-node
> gyp ERR! node -v v6.3.1
> gyp ERR! node-gyp -v v3.3.1
> gyp ERR! not ok

How can I force to use the node-gyp 3.4.0?

**Comment by aisbergde** [comment]
After installing the latest node-gyp
`npm install -g node-gyp@latest`

I replaced the content of
C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp
containing node-gyp -v v3.3.1
by
C:\Users\Germo\AppData\Roaming\npm\node_modules\node-gyp
containing node-gyp -v v3.4.0

Why there are different npm\node_modules on my system? Isn't there a different way? I don't know, but after this replacement I was able to install
`npm install -g pokemon-go-iv`
I got a lot of yellow warnings, but finaly it is here:
C:\Users\Germo\AppData\Roaming\npm\node_modules\pokemon-go-iv

Now I can run the pokemon-go-iv
It dosn't work, but this is another issue

**Comment by billyvg** [comment]
Not sure of windows directories, but `-g` means to install globally, so one of those directories is the global one. It looks like you have it working, but you could just wipe all node_modules directories, go to a new directory somewhere, `npm install pokemon-go-iv` and it'll install the package in`<current dir>\node_modules\pokemon-go-iv` and you can run it via `node .\node_modules\pokemon-go-iv\bin\app'
